development:
  adapter: postgresql
  encoding: unicode
  database: takeyourtime_development
  pool: 5
  username: <%= ENV['DB_USERNAME'] || ENV['USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: takeyourtime_test
  pool: 5
  username: <%= ENV['DB_USERNAME'] || ENV['USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>
  port: <%= ENV['DB_PORT'] || '5432' %>
